import { Translations } from './types';

export const TRANSLATIONS: Translations = {
  en: {
    initial_prompt: "Initial Prompt (Thesis)",
    improved_prompt: "Improved Prompt (Antithesis)",
    synthesized_prompt: "Synthesized Prompt (Synthesis)",
    improve_button: "Improve (Dialectical Negation)",
    select_prompt: "Select this Prompt",
    output_format: "Select Output Format",
    refinement_request: "Refinement Request",
    submit: "Submit",
    export: "Export",
    import: "Import",
    export_archive: "Export Archive",
    import_archive: "Import Archive",
    header_title: "Dialectical Prompt Synthesizer",
    header_subtitle: "Thesis • Antithesis • Synthesis",
    placeholder_enter: "Enter your rough prompt idea here...",
    interface_language: "Interface Language",
    target_prompt_language: "Target Prompt Language",
    translated_view: "Translation (Your Language)",
    original_view: "Prompt (Target Language)"
  },
  ru: {
    initial_prompt: "Исходный промпт (Тезис)",
    improved_prompt: "Улучшенный промпт (Антитезис)",
    synthesized_prompt: "Синтезированный промпт (Синтез)",
    improve_button: "Улучшить (диалектическое снятие)",
    select_prompt: "Выбрать этот промпт",
    output_format: "Выберите формат вывода",
    refinement_request: "Запрос на доработку",
    submit: "Отправить",
    export: "Экспорт",
    import: "Импорт",
    export_archive: "Экспорт архива",
    import_archive: "Импорт архива",
    header_title: "Диалектический Синтезатор Промптов",
    header_subtitle: "Тезис • Антитезис • Синтез",
    placeholder_enter: "Введите вашу идею для промпта здесь...",
    interface_language: "Язык интерфейса",
    target_prompt_language: "Язык генерации промпта",
    translated_view: "Перевод (Ваш язык)",
    original_view: "Промпт (Целевой язык)"
  },
  es: {
    initial_prompt: "Prompt Inicial (Tesis)",
    improved_prompt: "Prompt Mejorado (Antítesis)",
    synthesized_prompt: "Prompt Sintetizado (Síntesis)",
    improve_button: "Mejorar (Negación Dialéctica)",
    select_prompt: "Seleccionar este Prompt",
    output_format: "Seleccionar Formato de Salida",
    refinement_request: "Solicitud de Refinamiento",
    submit: "Enviar",
    export: "Exportar",
    import: "Importar",
    export_archive: "Exportar Archivo",
    import_archive: "Importar Archivo",
    header_title: "Sintetizador Dialéctico de Prompts",
    header_subtitle: "Tesis • Antítesis • Síntesis",
    placeholder_enter: "Introduce tu idea inicial aquí...",
    interface_language: "Idioma de la interfaz",
    target_prompt_language: "Idioma del prompt",
    translated_view: "Traducción (Tu idioma)",
    original_view: "Prompt (Idioma objetivo)"
  },
  zh: {
    initial_prompt: "初始提示（正题）",
    improved_prompt: "改进的提示（反题）",
    synthesized_prompt: "综合提示（合题）",
    improve_button: "改进（辩证否定）",
    select_prompt: "选择此提示",
    output_format: "选择输出格式",
    refinement_request: "改进请求",
    submit: "提交",
    export: "导出",
    import: "导入",
    export_archive: "导出存档",
    import_archive: "导入存档",
    header_title: "辩证提示合成器",
    header_subtitle: "正题 • 反题 • 合题",
    placeholder_enter: "在此输入您的初步提示想法...",
    interface_language: "界面语言",
    target_prompt_language: "目标提示语言",
    translated_view: "翻译（您的语言）",
    original_view: "提示（目标语言）"
  },
  hi: {
    initial_prompt: "प्रारंभिक प्रॉम्प्ट (थीसिस)",
    improved_prompt: "सुधारित प्रॉम्प्ट (एंटीथीसिस)",
    synthesized_prompt: "संश्लेषित प्रॉम्प्ट (संश्लेषण)",
    improve_button: "सुधारें (द्वंद्वात्मक नकार)",
    select_prompt: "इस प्रॉम्प्ट का चयन करें",
    output_format: "आउटपुट स्वरूप चुनें",
    refinement_request: "सुधार अनुरोध",
    submit: "प्रस्तुत करें",
    export: "निर्यात",
    import: "आयात",
    export_archive: "संग्रह निर्यात करें",
    import_archive: "संग्रह आयात करें",
    header_title: "द्वंद्वात्मक प्रॉम्प्ट सिंथेसाइज़र",
    header_subtitle: "थीसिस • एंटीथीसिस • संश्लेषण",
    placeholder_enter: "यहाँ अपना प्रारंभिक प्रॉम्प्ट विचार दर्ज करें...",
    interface_language: "इंटरफ़ेस भाषा",
    target_prompt_language: "लक्ष्य प्रॉम्प्ट भाषा",
    translated_view: "अनुवाद (आपकी भाषा)",
    original_view: "प्रॉम्प्ट (लक्ष्य भाषा)"
  }
};

export const INITIAL_STATE = {
  initial: { id: 'initial', content: '', isModified: false },
  improved: { id: 'improved', content: '', isModified: false },
  synthesized: { id: 'synthesized', content: '', isModified: false },
  selectedSource: null,
  selectedFormat: null,
  targetLanguage: 'en', // Default target generation language
  refinementRequest: '',
  isImproving: false,
  isSynthesizing: false,
  showImproved: false,
  showSynthesis: false,
};