export type LanguageCode = 'en' | 'ru' | 'es' | 'zh' | 'hi';

export enum PromptFormat {
  TYPESCRIPT = 'TypeScript Interface',
  XML = 'XML Tags',
  PSEUDOCODE = 'Pseudocode',
  COSTAR = 'COSTAR Framework'
}

export interface PromptData {
  id: string;
  content: string;
  isModified: boolean;
}

export interface AppState {
  initial: PromptData;
  improved: PromptData;
  synthesized: PromptData;
  selectedSource: 'initial' | 'improved' | null;
  selectedFormat: PromptFormat | null;
  targetLanguage: LanguageCode; // The language generated by AI
  refinementRequest: string;
  isImproving: boolean;
  isSynthesizing: boolean;
  showImproved: boolean;
  showSynthesis: boolean;
}

export interface ArchiveData {
  timestamp: number;
  state: AppState;
}

export interface TranslationSet {
  initial_prompt: string;
  improved_prompt: string;
  synthesized_prompt: string;
  improve_button: string;
  select_prompt: string;
  output_format: string;
  refinement_request: string;
  submit: string;
  export: string;
  import: string;
  export_archive: string;
  import_archive: string;
  header_title: string;
  header_subtitle: string;
  placeholder_enter: string;
  interface_language: string;
  target_prompt_language: string;
  translated_view: string;
  original_view: string;
}

export type Translations = Record<LanguageCode, TranslationSet>;